/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#eae1d4',
        'surface-container-high': '#f0e7da',
        'surface-container': '#f6eddf',
        'surface-container-low': '#fcf2e5',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#e2d9cc',
        'surface-bright': '#fff8f2',
        'surface-tint': '#37684d',
        'surface-variant': '#eae1d4',
        surface: '#fff8f2',
        background: '#fff8f2',
        primary: '#316248',
        'primary-container': '#4a7b5f',
        'primary-fixed': '#b9efcd',
        'primary-fixed-dim': '#9ed2b1',
        'on-primary': '#ffffff',
        'on-primary-container': '#dcffe7',
        'on-primary-fixed': '#002112',
        'on-primary-fixed-variant': '#1e5037',
        'inverse-primary': '#9ed2b1',
        secondary: '#526259',
        'secondary-container': '#d3e4d8',
        'secondary-fixed': '#d6e7db',
        'secondary-fixed-dim': '#bacbbf',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#57665d',
        'on-secondary-fixed': '#101e17',
        'on-secondary-fixed-variant': '#3b4a41',
        tertiary: '#595953',
        'tertiary-container': '#72716b',
        'tertiary-fixed': '#e5e2db',
        'tertiary-fixed-dim': '#c9c6c0',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f9f6ef',
        'on-tertiary-fixed': '#1c1c18',
        'on-tertiary-fixed-variant': '#474742',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#717972',
        'outline-variant': '#c0c9c1',
        'on-surface': '#1f1b13',
        'on-surface-variant': '#414943',
        'inverse-surface': '#343027',
        'inverse-on-surface': '#f9efe2',
        'on-background': '#1f1b13',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        handwritten: ['"Nanum Pen Script"', 'cursive'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
